
% Data set name
dataset = 'Drishti';
options.numTrials = 200;

% Tests to compare
testsToCompare = { ...              
%      strcat('multiple-trials', filesep, 'original', filesep, 'square', filesep, 'down-aug', filesep, 'L2'), ...
%      strcat('multiple-trials', filesep, 'vesselInpainted', filesep, 'square', filesep, 'down-aug', filesep, 'L2'), ...
      strcat('multiple-trials', filesep, 'original', filesep, 'square', filesep, 'fov-crop-down-withCDR', filesep, 'L2'), ...
%      strcat('multiple-trials', filesep, 'vesselInpainted', filesep, 'square', filesep, 'fov-crop-down-aug', filesep, 'L2'), ...
%      strcat('multiple-trials', filesep, 'vessels', filesep, 'square', filesep, 'down', filesep, 'L2'), ...
%      strcat('multiple-trials', filesep, 'vessels', filesep, 'square', filesep, 'down-aug-90', filesep, 'L2'), ...
%      strcat('multiple-trials', filesep, 'vessels', filesep, 'square', filesep, 'down-aug', filesep, 'L2'), ...
%      strcat('multiple-trials', filesep, 'original', filesep, 'square', filesep, 'od-down-aug', filesep, 'L2'), ...
%      strcat('multiple-trials', filesep, 'vesselInpainted', filesep, 'square', filesep, 'od-down-aug', filesep, 'L2'), ...  
%      strcat('multiple-trials', filesep, 'original', filesep, 'square', filesep, 'only-od-down-aug', filesep, 'L2'), ...
%      strcat('multiple-trials', filesep, 'vesselInpainted', filesep, 'square', filesep, 'only-od-down-aug', filesep, 'L2'), ...  
      strcat('multiple-trials', filesep, 'only-CDR'), ... 
};
% For the legends
descriptions = { ...                
%      'Original with vessels - L2 - Aug. 45º', ...
%      'Original without vessels - L2 - Aug. 45º', ...
      'FOV with vessels - L2 - Not aug.', ...
%      'FOV without vessels - L2 - Aug. 45º', ...
%      'Binary vessels - L2', ...
%      'Binary vessels - L2 - Aug. 90º', ...
%      'Binary vessels - L2 - Aug. 45º', ...
%      'PPA with vessels - L2 - Aug. 45º', ...
%      'PPA without vessels - L2 - Aug. 45º', ...
%      'ONH with vessels - L2 - Aug. 45º', ...
%      'ONH without vessels - L2 - Aug. 45º', ...     
      'CDR', ... 
};

[ret, hostname] = system('hostname');
hostname = strtrim(lower(hostname));
% Lab computer
if strcmp(hostname, 'orlando-pc')
    % Folder where the results are saved
    resultsFolder = 'C:\Users\USUARIO\Dropbox\RetinalImaging\Writing\cnn2015paper\results';
elseif strcmp(hostname, 'animas')
    % Folder where the results are saved
    resultsFolder = '/home/ignacioorlando/nacho-research/cnn2015glaucoma/results';
else
    % Folder where the results are saved
    resultsFolder = 'G:\Dropbox\RetinalImaging\Writing\cnn2015paper\results';
end
resultsFolder = strcat(resultsFolder, filesep, dataset);


figure;
hold on;
grid on;
box on;
% For each type of test I want to compare
for i = 1 : length(testsToCompare)
    
    % Open results matrix
    currentTest = testsToCompare{i};
    load(strcat(resultsFolder, filesep, currentTest, filesep, 'results.mat'));
    
    % Generate ROC curve
    [AUC, AVR_X, AVR_Y, MCC, SCORE] = generateMeanROCCurve(results.scores, results.labelsVals, options.numTrials);
    descriptions{i} = strcat(descriptions{i}, ' - AUC=', num2str(AUC));
    % Plot it
    plot(AVR_X, AVR_Y);
    
end
legend(descriptions, 'Location', 'southeast');
xlabel('FPR (False Positive Rate)');
ylabel('TPR (True Positive Rate)');
hold off