
warning('off','all');

[ret, hostname] = system('hostname');
hostname = strtrim(lower(hostname));

% SET DATA SET NAME
%datasetsNames = {'Drishti'};
datasetsNames = {'GlaucomaDB'};
% SET FOLDER
if strcmp(hostname, 'orlando-pc')
    % Root dir where the data sets are located
    rootDatasets = 'C:\_glaucoma\datasets';
    % Root dir where the segmentations are located
    rootSegmentations = 'C:\_glaucoma\datasets';
    % Root folder where the results are going to be stored
    rootResults = 'C:\SharedFolderWithUbuntu';
end

crop_images = 0;

preprocessings_methods = [ ...
    1 ...
    1 ...
    1 ...
    1 ...
    1 ...
    1 ...
    1 ...
    1 ...
    1 ...
    1 ...
];    
preprocessings_names = { ...
    'color'...
    'color-inp' ...
    'green' ...
    'green-inp' ...
    'norm-color'...
    'norm-color-inp'...
    'clahe-color'...
    'clahe-color-inp'...
    'green-clahe'...
    'green-clahe-inp'...
};   