
% Data set
%dataset = 'Drishti';
dataset = 'GlaucomaDB';

% Downscale factors
%downscale_factor = 0.336760925;
downscale_factor = 0.409375;


% Crop types
crop_types = { ...
    'im-fov-crop' ...
    'im-od' ...
    'im-only-od' ...
};

root_data_path = 'C:\SharedFolderWithUbuntu';
root_crops_path = 'C:\_glaucoma\_resources\crops';

% preprocessing methods
preprocessings_names = { ...
    'color'...
    'color-inp' ...
    'green' ...
    'green-inp' ...
    'norm-color'...
    'norm-color-inp'...
    'clahe-color'...
    'clahe-color-inp'...
    'green-clahe'...
    'green-clahe-inp'...
};  


% Path where the images are
image_path = fullfile(root_data_path, dataset);
% Path with the crops
crops_path = fullfile(root_crops_path, dataset, 'square');
% Path where the results will be saved
output_path = fullfile('C:\SharedFolderWithUbuntu', dataset);
